ARG IMAGE=docker.io/vllm/vllm-openai:v0.8.5.post1
FROM ${IMAGE}

RUN apt-get update && apt-get install -y \
    python3 python3-pip git curl \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN uv pip install --system --no-cache vllm[audio]==0.8.5.post1 librosa==0.11.0 

ENV VLLM_LOGGING_LEVEL=DEBUG \
    VLLM_TRACE_FUNCTION=1 \
    MODEL_NAME=openai/whisper-tiny

ENTRYPOINT ["sh", "-c" ]
CMD [ "vllm serve ${MODEL_NAME} --task transcription" ]
